# Generated by Django 3.2.5 on 2021-07-10 03:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20210710_1046'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='like',
            name='like_post',
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 10, 12, 37, 46, 632093)),
        ),
    ]
