# Generated by Django 3.2.5 on 2021-07-13 05:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_auto_20210710_1237'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='friends',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='friends',
            name='following',
        ),
        migrations.AddField(
            model_name='friends',
            name='followed',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='receive', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friends',
            name='follower',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='send', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 13, 14, 8, 4, 165682)),
        ),
        migrations.AddConstraint(
            model_name='friends',
            constraint=models.UniqueConstraint(fields=('follower', 'followed'), name='friends'),
        ),
    ]
